name: flutter_base_bloc
description: A new Flutter plugin project.
version: 0.0.1
homepage: https://github.com/channdara/flutter_base_bloc

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mastertipsy.flutter_base_bloc
        pluginClass: FlutterBaseBlocPlugin
      ios:
        pluginClass: FlutterBaseBlocPlugin
      linux:
        pluginClass: FlutterBaseBlocPlugin
      macos:
        pluginClass: FlutterBaseBlocPlugin
      windows:
        pluginClass: FlutterBaseBlocPluginCApi